version: '3'
services:
  db:
   container_name:  DockerComposeTest-DB
   image: postgres:16-alpine
   restart: always
   ports: 
     - 5432:5432
   volumes:
     - ./postgres/init:/docker-entrypoint-initdb.d
   environment:
     - POSTGRES_DB=productDB
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
  java:
   container_name: DockerComposeTest-API
   build: .
   ports:
    - 80:8080
   tty: true
volumes:
 dockerComposeTestVol: